import type { DVCMonthConfig } from "./months";

/** All six Jul–Dec months for experimental demo builds */
export const EXPERIMENTAL_DVC_MONTHS: DVCMonthConfig[] = [
  {
    slug: "july",
    name: "July",
    monthNum: 7,
    year: 2026,
    days: 31,
    theme: "Dominion to Overflow · 31 days",
    ready: true,
    gradient: "linear-gradient(160deg,#0c2748,#1b4d86)",
    navy: "#0f2d52",
    bright: "#2f7bd6",
    gold: "#c69b3a",
    startWeekday: 3,
  },
  {
    slug: "august",
    name: "August",
    monthNum: 8,
    year: 2026,
    days: 31,
    theme: "The Anointing to New Beginnings · 31 days",
    ready: true,
    gradient: "linear-gradient(160deg,#1a0840,#4c1d95)",
    navy: "#2e1065",
    bright: "#9333ea",
    gold: "#c69b3a",
    startWeekday: 6,
  },
  {
    slug: "september",
    name: "September",
    monthNum: 9,
    year: 2026,
    days: 30,
    theme: "Divine Direction to Finishing Well · 30 days",
    ready: true,
    gradient: "linear-gradient(160deg,#062825,#0f766e)",
    navy: "#0c3b3a",
    bright: "#14b8a6",
    gold: "#c0772e",
    startWeekday: 2,
  },
  {
    slug: "october",
    name: "October",
    monthNum: 10,
    year: 2026,
    days: 31,
    theme: "Holy Fire to The Finished Work · 31 days",
    ready: true,
    gradient: "linear-gradient(160deg,#3f060a,#9f1239)",
    navy: "#5b0d12",
    bright: "#dc2626",
    gold: "#c69b3a",
    startWeekday: 4,
  },
  {
    slug: "november",
    name: "November",
    monthNum: 11,
    year: 2026,
    days: 30,
    theme: "A Grateful Heart to Gratitude That Multiplies · 30 days",
    ready: true,
    gradient: "linear-gradient(160deg,#0a2414,#15803d)",
    navy: "#13331f",
    bright: "#22a85a",
    gold: "#a9772f",
    startWeekday: 0,
  },
  {
    slug: "december",
    name: "December",
    monthNum: 12,
    year: 2026,
    days: 31,
    theme: "The Victory of the Cross to Crossing Over · 31 days",
    ready: true,
    gradient: "linear-gradient(160deg,#060d20,#1e3a8a)",
    navy: "#0a1633",
    bright: "#3b5bdb",
    gold: "#c9a84c",
    startWeekday: 2,
  },
];

export function getExperimentalMonth(slug: string): DVCMonthConfig | undefined {
  return EXPERIMENTAL_DVC_MONTHS.find((m) => m.slug === slug.toLowerCase());
}
